# Generated by Django 4.1.4 on 2022-12-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название вопроса"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                ("answer", models.TextField(null=True, verbose_name="Ответ")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Не решенный"),
                            (2, "Решённый"),
                            (3, "Замороженный"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тикет",
                "verbose_name_plural": "Тикеты",
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текс сообщения")),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                        verbose_name="Тикет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение к тикету",
                "verbose_name_plural": "Сообщения к тикету",
            },
        ),
    ]
